In [134]:
import torch
import torch.optim as optim
from flair.embeddings import WordEmbeddings
from flair.data import Sentence
import pandas as pd
import numpy as np
from torch import nn
import torch.nn.functional as F
from torch.nn.modules.distance import PairwiseDistance

In [3]:
torch.Tensor([1,2,3]) 

tensor([1., 2., 3.])

In [182]:
X = torch.rand(100,10)

In [183]:
b = torch.rand(10)

In [184]:
y = X @ b + torch.randn(100)/100

In [225]:
class LogReg(nn.Module):
    def __init__(self, input_size, output_size):
        super(LogReg, self).__init__()
        self.L1 = nn.Linear(input_size, output_size)
        
    def forward(self, X):
        return self.L1(X) # # torch.sigmoid(self.L1(X))

In [233]:
model = LogReg(10,1)

In [234]:
opt = optim.Adam(model.parameters())

In [235]:
y = y.reshape(y.shape[0],1)

In [237]:
for i in range(10000):
    model.zero_grad()
    y_pred = model.forward(X)
    L = torch.sum(torch.pow(y - y_pred, 2))
    L.backward()
    opt.step()
    if (i % 1000) == 0 : print(L)

tensor(0.0084, grad_fn=<SumBackward0>)
tensor(0.0084, grad_fn=<SumBackward0>)
tensor(0.0084, grad_fn=<SumBackward0>)
tensor(0.0084, grad_fn=<SumBackward0>)
tensor(0.0084, grad_fn=<SumBackward0>)
tensor(0.0084, grad_fn=<SumBackward0>)
tensor(0.0084, grad_fn=<SumBackward0>)
tensor(0.0084, grad_fn=<SumBackward0>)
tensor(0.0084, grad_fn=<SumBackward0>)
tensor(0.0084, grad_fn=<SumBackward0>)


In [1]:
from __future__ import print_function
import torch

In [2]:
x = torch.empty(5, 3)
print(x)

tensor([[4.5085e+16, 5.8270e-10, 2.5029e-12],
        [1.4585e-19, 4.9153e-14, 5.5095e-14],
        [1.3563e-19, 1.7753e+28, 1.3458e-14],
        [4.0326e-11, 1.6410e-07, 4.0274e-11],
        [1.6803e-04, 4.0274e-11, 1.6875e-07]])


In [3]:
x = torch.rand(5, 3)
print(x)

tensor([[0.2573, 0.2490, 0.4267],
        [0.3803, 0.3008, 0.2288],
        [0.4290, 0.7771, 0.3556],
        [0.9394, 0.8396, 0.3381],
        [0.6089, 0.6613, 0.3520]])


In [12]:
x = torch.ones(2, 2, requires_grad=True)
print(x)

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)


In [13]:
y=x+2

In [16]:
z=y*y*3

In [18]:
out=z.mean()

In [19]:
out.backward()

In [20]:
x.grad

tensor([[4.5000, 4.5000],
        [4.5000, 4.5000]])

In [21]:
import torch
import torch.nn as nn
import torch.nn.functional as F

In [24]:
class Net(nn.Module):

    def __init__(self):
        super(Net, self).__init__()
        # 1 input image channel, 6 output channels, 3x3 square convolution
        # kernel
        self.conv1 = nn.Conv2d(1, 6, 3)
        self.conv2 = nn.Conv2d(6, 16, 3)
        # an affine operation: y = Wx + b
        self.fc1 = nn.Linear(16 * 6 * 6, 120)  # 6*6 from image dimension
        self.fc2 = nn.Linear(120, 84)
        self.fc3 = nn.Linear(84, 10)

    def forward(self, x):
        # Max pooling over a (2, 2) window
        x = F.max_pool2d(F.relu(self.conv1(x)), (2, 2))
        # If the size is a square you can only specify a single number
        x = F.max_pool2d(F.relu(self.conv2(x)), 2)
        x = x.view(-1, self.num_flat_features(x))
        x = F.relu(self.fc1(x))
        x = F.relu(self.fc2(x))
        x = self.fc3(x)
        return x

    def num_flat_features(self, x):
        size = x.size()[1:]  # all dimensions except the batch dimension
        num_features = 1
        for s in size:
            num_features *= s
        return num_features


In [25]:
net = Net()
print(net)

Net(
  (conv1): Conv2d(1, 6, kernel_size=(3, 3), stride=(1, 1))
  (conv2): Conv2d(6, 16, kernel_size=(3, 3), stride=(1, 1))
  (fc1): Linear(in_features=576, out_features=120, bias=True)
  (fc2): Linear(in_features=120, out_features=84, bias=True)
  (fc3): Linear(in_features=84, out_features=10, bias=True)
)


In [30]:
x=torch.rand(3,4)

In [34]:
x=x-0.5